apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  containers:
  - name: box
    image: mtardy/koolbox:v0.1.4
    args:
    - "kdigger dig all && sleep infinity"
    securityContext:
      privileged: true