apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  selector:
    matchLabels:
      run: auth-api
  replicas: 1
  template:
    metadata:
      labels:
        run: auth-api
    spec:
      containers:
        - name: app
          image: atemate/webinar-k8sec_auth-api:v1.0
          ports:
          - containerPort: 8080
          env:
            name: REDIRECT_HOST
            value: http://image-api
          command:
            - "python"
            - "app.py"
