apiVersion: v1
kind: Service
metadata:
  name: auth-api
  labels:
    run: auth-api
spec:
  selector:
    run: auth-api
  # type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
