apiVersion: v2
appVersion: 20.6.0
dependencies:
- condition: nginx-ldapauth-proxy.enabled
  name: nginx-ldapauth-proxy
  repository: https://charts.helm.sh/stable
  version: 0.1.4
description: Kubernetes Web View
home: https://kube-web-view.readthedocs.io/
icon: https://codeberg.org/repo-avatars/1013-79c19f23d3617c23ec9f668a3c5fe0c5
keywords:
- dashboard
- utility
- monitoring
- kubernetes
name: kube-web-view
sources:
- https://codeberg.org/hjacobs/kube-web-view/
version: 0.0.4
