apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  selector:
    matchLabels:
      run: auth-api
  replicas: 1
  template:
    metadata:
      labels:
        run: auth-api
    spec:
      containers:
      - name: app
        image: atemate/webinar-k8sec_auth-api:v1.3
        ports:
        - containerPort: 8080
        env:
        - name: SECRET_KEY
          value: secret123  # TODO: mount from a secret
        - name: REDIRECT_HOST
          value: http://vulnapp-images.seck8s.slurm.io/
        command: ["python", "app.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
  labels:
    run: auth-api
spec:
  selector:
    run: auth-api
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-api
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: vulnapp-auth.seck8s.slurm.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth-api
            port:
              number: 80
