apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-emali-service
spec:
  selector:
    matchLabels:
      run: mock-emali-service
  replicas: 1
  template:
    metadata:
      labels:
        run: mock-emali-service
    spec:
      containers:
      - name: app
        image: atemate/webinar-k8sec_mock-emali-service:v1.3
        ports:
        - containerPort: 8080
        command: ["python", "app.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: mock-emali-service
  labels:
    run: mock-emali-service
spec:
  selector:
    run: mock-emali-service
  ports:
  - port: 80
    targetPort: 8080
