apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: mock-payload
  name: db-secret
data:
  db-username: YWRtaW4=
  db-password: cGFzc3dvcmQK
  db-secret-config: bWF4bWVtb3J5IDJtYgptYXhtZW1vcnktcG9saWN5IGFsbGtleXMtbHJ1